### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by aleksacv** [notify-events/node-red#3]
Hi, 
I have very simple flow and I'm always getting following errors

"Error: Unknown fieldType: ne_priority"
"Error: Unknown fieldType: ne_level"
I'm running Node-Red 3.0.0

![Capture](https://user-images.githubusercontent.com/65966772/181870690-92f62472-1d49-411c-af46-511bf307a5d6.JPG)

**Comment by matrozov** [comment]
Thanks for the report. Fixed in version 1.1.1

**Comment by aleksacv** [comment]
Hi, first thanks for creating the new version. 
I'm not sure if you can help or have some guidance, but I'm using node-red in Home Assistant. When I go to the palette manager to install new version, I still can see only 1.1.0
![image](https://user-images.githubusercontent.com/65966772/182759649-72fe1f03-517f-4722-9618-6f72e5b30fbc.png)

**Comment by matrozov** [comment]
> Hi, first thanks for creating the new version. I'm not sure if you can help or have some guidance, but I'm using node-red in Home Assistant. When I go to the palette manager to install new version, I still can see only 1.1.0 ![image](https://user-images.githubusercontent.com/65966772/182759649-72fe1f03-517f-4722-9618-6f72e5b30fbc.png)

Thank you for your comment. Please check again, version 1.1.1 should be available

**Comment by aleksacv** [comment]
Thanks, it works now.
